### ISSUE TITLE
not able to update the signed_up_at user attribute of user

### ISSUE THREAD

**Issue by deepak786** [deepak786/intercom_flutter#107]
There is a user attribute of the user in Intercom that we can update like signed_up_at, etc.
But there is no way to update the same in the Flutter plugin.
If I use 
```
Intercom.updateUser(customAttributes: {
      'signed_up_at': seconds,
});
```
then it will create a new custom attribute in the Intercom.

**Comment by deepak786** [comment]
@Zazo032 please check and update.

**Comment by deepak786** [comment]
Is the package being maintained or not? It's been 2 days but there is no update on this issue.

**Comment by Spikes042** [comment]
> Is the package being maintained or not? It's been 2 days but there is no update on this issue.

It's an open-source project. I think you can fire up Android Studio anytime and contribute a patch. We'd all really appreciate that

**Comment by deepak786** [comment]
@Spikes042 created the pull request https://github.com/v3rm0n/intercom_flutter/pull/108

**Comment by deepak786** [comment]
using 
```
dependency_overrides:
  intercom_flutter:
    git:
      url: https://github.com/deepak786/intercom_flutter.git
      ref: signedUpAt
```

until it is merged in master
