### ISSUE TITLE
Custom bots not appearing after first visit. 

### ISSUE THREAD

**Issue by aasamaroo** [deepak786/intercom_flutter#147]
I am having an issue with my android app where after I engage with a custom bot once, it will not appear again. I have selected the option to resend the bot for next visit, but the bot still will not send. After speaking to an intercom representative they are saying that our SDK is outdated. However, after talking to my head developer he has informed me that we are using the most recent version of the intercom flutter. Is this an issue with flutter, or intercom? Please let me know.

**Comment by deepak786** [comment]
@aasamaroo In the current intercom_flutter version `3.2.1`, the Android Intercom SDK version used is 
`io.intercom.android:intercom-sdk:8.2.+`

The latest Intercom Android SDK version is `9.2.0`
https://github.com/intercom/intercom-android/blob/master/CHANGELOG.md


To make sure that the latest Intercom SDK version will resolve your issue, override the intercom_flutter dependency in your flutter project
```
dependency_overrides:
  intercom_flutter:
    git:
      url: https://github.com/deepak786/intercom_flutter.git
      ref: Carousel_Article_flutter
      path: intercom_flutter
```

Here the latest Intercom Android SDK version `9.2.0` is used. So try that.
