### ISSUE TITLE
Bug introduced due semantic versioning misconception

### ISSUE THREAD

**Issue by emanuel-braz** [deepak786/intercom_flutter#236]
Hi, I noticed that a bug was introduced in `intercom_flutter:5.3.0` version, at the moment when there was a breaking change in `intercom_flutter_platform_interface`.

When a breaking change is introduced, you need to update the `major` of the semantic versioning, so that the control tools know which dependencies it can and cannot update.

Note that from version `1.0.1` it went up to version `1.1.0`, and the correct thing would be to go up to version `2.0.0`.
![Screen Shot 2022-05-02 at 12 42 34](https://user-images.githubusercontent.com/3827308/166267127-846e46ea-9c33-4a5a-ac23-cc3c2e2096fb.png)

This helps avoid runtime crashes due to incompatible dependencies, like this error that is happening in `5.3.0`:

`MissingPluginException(No implementation found for method loginIdentifiedUserWithUserId on channel [maido.io/intercom](http://maido.io/intercom))`

This is a really nice reference guide about versioning, please have a look:
https://vivek-kaushal.medium.com/versioning-your-software-correctly-a-guide-to-semantic-versioning-c9f457da6f4b

**Workaround (this forces to lock the sub-dependencies):**
```yaml
dependencies:
  intercom_flutter: ^5.3.0

dependency_overrides:
  intercom_flutter_platform_interface: 1.0.1
  intercom_flutter_web: 0.0.4
```
