### ISSUE TITLE
sendTokenToIntercom is undefined in latest version 2.0.3

### ISSUE THREAD

**Issue by masashi-sutou** [deepak786/intercom_flutter#28]
## description

`sendTokenToIntercom` is undefined in the latest version. 

I think this commits(1f7edf4dc52e6db07b39074b9157c1b2400b987d) is not included in the latest version.

Please release the package again.

## workaround

```
intercom_flutter:
  git:
    url: git://github.com/v3rm0n/intercom_flutter
    ref: master
```
