### ISSUE TITLE
Incompatible with UUID v4 

### ISSUE THREAD

**Issue by pixnbit** [deepak786/intercom_flutter#364]
Because no versions of intercom_flutter match >8.0.1 <9.0.0 and intercom_flutter 8.0.1 depends on intercom_flutter_web ^1.0.0, intercom_flutter ^8.0.1 requires intercom_flutter_web ^1.0.0.
Because intercom_flutter_web 1.0.0 depends on uuid ^3.0.7 and no versions of intercom_flutter_web match >1.0.0 <2.0.0, intercom_flutter_web ^1.0.0 requires uuid ^3.0.7.
Thus, intercom_flutter ^8.0.1 requires uuid ^3.0.7.
So, because shift_flow depends on both intercom_flutter ^8.0.1 and uuid ^4.1.0, version solving failed.

You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on uuid: flutter pub add uuid:^3.0.7

**Comment by vlazdra** [comment]
Hi @pixnbit I've created an update for this specific issue and until it get's merged we are a bit stuck.

In the meantime you can use the branch I've added as a PR directly in your project to overcome this issue for the time being.

In your `pubspec.yaml` you can add this:
```yaml

dependency_overrides:
  intercom_flutter_web:
    git:
      url: https://github.com/vlazdra/intercom_flutter
      ref: uuid-update
      path: intercom_flutter_web
```
