### ISSUE TITLE
Tapping on push notification restarts backgrounded app on Android

### ISSUE THREAD

**Issue by karim-cardeo** [deepak786/intercom_flutter#414]
Hi folks,

I have recently found an issue which occurs when tapping on a push notification sent by Intercom on Android if the app is in the background. 

Steps to replicate:

Given I have an Android Flutter app with the intercom_flutter package installed and correctly setup,
And I have launched the app and put it in the background,
When I receive a push notification from Intercom,
And I tap on the push notification,
Then I am routed to the Intercom messenger,
And the app is restarted.

The expected result should instead be that the app is brought back from the background without restarting.

I have been able to replicate this issue on a brand new Flutter project that uses the latest version of Flutter (3.19.2) and of the intercom_flutter package (8.1.1).

Below is the code of the only screen in my test project (sensitive data redacted):

```
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/material.dart';
import 'package:intercom_flutter/intercom_flutter.dart';

class HomeScreen extends StatelessWidget {
  const HomeScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: ElevatedButton(
          onPressed: tap,
          child: const Text('Click me'),
        ),
      ),
    );
  }

  Future<void> tap() async {
    await FirebaseMessaging.instance.requestPermission();

    await Intercom.instance.initialize('appId', androidApiKey: 'apiKey');
    await Intercom.instance.setUserHash('userHash');
    await Intercom.instance.loginIdentifiedUser(userId: 'userId');

    await Future.delayed(const Duration(milliseconds: 1500));

    final token = await FirebaseMessaging.instance.getToken();
    if (token == null) return;
    await Intercom.instance.sendTokenToIntercom(token);

    await Intercom.instance.displayMessenger();
  }
}
```

And here is the `pubspec.yaml` file which shows all of the dependencies on this project:

```
name: intercom_nav_test
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intercom_flutter: ^8.1.1
  firebase_core: ^2.26.0
  firebase_messaging: ^14.7.18
  flutter_native_splash: ^2.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
```

Finally, I have attached below a video of the issue captured on my Android device (the blue screen that appears is my mock splash screen, there to indicate the app is restarting):

https://github.com/v3rm0n/intercom_flutter/assets/117079582/89aaa8cf-2eee-450e-94fc-11ac88998c0e
