### ISSUE TITLE
Intercom iOS 16.6.2 missing in intercom_flutter releases

### ISSUE THREAD

**Issue by orestesgaolin** [deepak786/intercom_flutter#425]
Starting from [9.0.0](https://pub.dev/packages/intercom_flutter/changelog#900) the minimum Intercom iOS library is 17.0.0. However, the previous version of the plugin ([8.1.3](https://pub.dev/packages/intercom_flutter/changelog#813)) is using Intercom iOS 16.6.1.

Intercom released version [16.6.2](https://github.com/intercom/intercom-ios/releases/tag/16.6.2) to address the privacy manifest issue.

However, because the plugin is using fixed version (16.6.1), it's not possible to override the pod dependency like follows:

```
target 'Runner' do
  use_frameworks!
  use_modular_headers!
  pod 'Intercom', '16.6.2'
end
```

as calling `pod update Intercom` results with:

```
[!] CocoaPods could not find compatible versions for pod "Intercom":
  In Podfile:
    Intercom (= 16.6.2)

    intercom_flutter (from `.symlinks/plugins/intercom_flutter/ios`) was resolved to 7.5.0, which depends on
      Intercom (= 16.6.1)

Specs satisfying the `Intercom (= 16.6.2), Intercom (= 16.6.1)` dependency were found, but they required a higher minimum deployment target.
```

To resolve it I created a fork out of 8.1.3 commit [here](https://github.com/orestesgaolin/intercom_flutter/tree/update-to-16.6.2). It bumps the iOS SDK to 16.6.2

```yaml
dependencies:
  intercom_flutter:
    git:
      url: https://github.com/orestesgaolin/intercom_flutter.git
      ref: 8.1.4
      path: intercom_flutter
```

For people that need to stay on previous version of Intercom SDK you can use the above fork.
